name: Build and Deploy to GitHub Pages

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy Unity WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache the Library folder
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build Unity project directly into build directory
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildPath: build/WebGL

      # Zip the WebGL build
      - name: Zip WebGL build
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r WebGL.zip build/WebGL

      # Upload WebGL Build ZIP as artifact
      - name: Upload WebGL Build ZIP
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build-ZIP
          path: WebGL.zip

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL

      # Checkout the gh-pages branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      # Ensure gh-pages branch is checked out
      - name: Verify Branch
        run: |
          echo "Currently on branch: $(git branch --show-current)"

      # Move WebGL build to location of .nojekyll
      - name: Move WebGL build to location of .nojekyll
        run: |
          TARGET_DIR=$(sudo find . -name ".nojekyll" -exec dirname {} \;)
          echo "Found .nojekyll in ${TARGET_DIR}"
          sudo rsync -av --remove-source-files WebGL/ $TARGET_DIR/
          sudo rm -rf WebGL

      # Ensure there are changes to commit
      - name: Check for changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Move WebGL build to location of .nojekyll"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Wait and verify changes
      - name: Sleep and Verify Changes
        run: |
          echo "Waiting for 30 seconds to ensure push is reflected"
          sleep 30
          git pull origin gh-pages
          echo "Final directory structure:"
          ls -R
