name: Build and Deploy to GitHub Pages

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy Unity WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache the Library folder
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build Unity project directly into build directory
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildPath: build/WebGL

      # Zip the WebGL build
      - name: Zip WebGL build
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r WebGL.zip build/WebGL

      # Upload WebGL Build ZIP as artifact
      - name: Upload WebGL Build ZIP
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build-ZIP
          path: WebGL.zip

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL

      # Switch and clean gh-pages branch
      - name: Clean gh-pages branch
        run: |
          echo "Switching to gh-pages branch"
          git fetch origin
          git switch gh-pages
          git reset --hard
          sudo git clean -d -x -f
          sudo rm -r *
          git add -A
          git commit -m "Cleaning branch"
          git push

      # Apply stashed files (if any)
      - name: Apply stashed files
        run: |
          echo "Applying stash"
          if git stash list | grep -q 'stash@{0}'; then
            git stash apply stash@{0}
          else
            echo "No stash to apply"
          fi

      # Move files to root directory
      - name: Move files to root directory
        run: |
          cd build/WebGL
          sudo cp -r * ../../
          cd ../../
          sudo rm -r build
          ls
          pwd
          
      # Push deployment to gh-pages branch
      - name: Push deployment to gh-pages branch
        run: |
          pwd
          git status
          git add -A
          git commit -m "Deployment"
          git push
          git reset --hard
          sudo git clean -d -x -f
