name: Build Unity WebGL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/unity-setup@v2.0
      with:
        unityVersion: 2022.3.3f1

    - name: Build WebGL
      uses: game-ci/unity-builder@v2.0
      with:
        targetPlatform: WebGL

    - name: Upload WebGL Build
      uses: actions/upload-artifact@v2
      with:
        name: WebGL-Build
        path: build/WebGL
