name: Build and Deploy to GitHub Pages

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy Unity WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache the Library folder
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build Unity project
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildPath: build/WebGL

      # Create a ZIP of the WebGL build
      - name: Create ZIP of WebGL build
        run: |
          zip -r build/WebGL.zip build/WebGL

      # Save ZIP artifact
      - name: Upload WebGL Build ZIP
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build-ZIP
          path: build/WebGL.zip

      # Move build files to the root directory
      - name: Move build files to root
        run: |
          mv build/WebGL/* .

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
