name: Build and Deploy to GitHub Pages

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy Unity WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache the Library folder
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build Unity project directly into build directory
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildPath: build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build

      # Zip the WebGL build
      - name: Zip WebGL build
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r WebGL.zip build

      # Upload WebGL Build ZIP as artifact
      - name: Upload WebGL Build ZIP
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build-ZIP
          path: WebGL.zip
